email:
  filters:
    subject_keywords: ["test", "testing", "test_api"]
    sender_domains: ["gmail.com"]

sharepoint:
  client_id: ${CLIENT_ID}
  client_secret: ${CLIENT_SECRET}
  tenant_id: ${TENANT_ID}
  site_name: ${SITE_NAME}
  site_url: "https://atiumcapital.sharepoint.com/sites/${SITE_NAME}"

# -------------------- Heron API Configuration --------------------
heron:
  api_base_url: "https://app.herondata.io/api"
  api_key: ${HERON_API_KEY}

# -------------------- Storage Configuration --------------------
storage:
  base_download_dir: "downloads"